### ISSUE TITLE
Make updates more user-friendly

### ISSUE THREAD

**Issue by jrbartola** [CryptoSignal/crypto-signal#161]
When an update to the main branch occurs, notify users in their crypto-signal console that an update is available and provide them an easy way to get the latest deployment without having to manually pull from the repository

**Comment by shads2** [comment]
Could do this, honestly though I would rather solve the problem of users having to build their own docker images first and maybe start using the releases feature.

**Comment by shads2** [comment]
Implemented in https://github.com/CryptoSignal/crypto-signal/pull/186
