### ISSUE TITLE
Bug: ichimoku = false and still generate the error

### ISSUE THREAD

**Issue by xonline** [CryptoSignal/crypto-signal#172]
<img width="293" alt="screen shot 2018-02-20 at 4 13 53 pm" src="https://user-images.githubusercontent.com/31034272/36409664-e3fa3392-1660-11e8-8699-b5bd29392e26.png">
<img width="344" alt="screen shot 2018-02-20 at 5 09 08 pm" src="https://user-images.githubusercontent.com/31034272/36409665-e42e87aa-1660-11e8-99c3-d5997947ee57.png">

**Comment by shads2** [comment]
Implemented in https://github.com/CryptoSignal/crypto-signal/pull/186 waiting for review
