### ISSUE TITLE
Feature Request: Multiple EMA's

### ISSUE THREAD

**Issue by robe** [CryptoSignal/crypto-signal#177]
For EMA's I'm hoping to get an 8, 13, 21, and 55 day moving average. Mostly I want to know when the 55 day MA crosses the 8 day MA. Thanks!

**Comment by cryptohanaan** [comment]
This is a great feature request and very needed.
A single EMA (or SMA) by itself has far less value than when in pairs.
To be adopted by traders or to create trading tools, an ability to track multiple EMA/SMA lines and determine when one crosses over or under the other is essential.

**Comment by jrbartola** [comment]
Moving average crossovers have now been implemented #215

**Comment by cryptohanaan** [comment]
Thank u! Cant wait to dig in
