### ISSUE TITLE
Can you please help me how to change bittrex to binance exchange ? 

### ISSUE THREAD

**Issue by himanshubotadra** [CryptoSignal/crypto-signal#178]
I was able to change the market pairs but I would appreciate if you can please help me with steps to change from bittrex to binance please. I am getting error if I am adding below line ..
EXCHANGES_BITTREX_REQUIRED_ENABLED=false and EXCHANGES_BITFINEX_REQUIRED_ENABLED=true
I am aware the above is for Bitfinex but it still it doesnt change to bitfinex.

Error: Traceback (most recent call last):
  File "app.py", line 45, in <module>
    main()
  File "app.py", line 20, in main
    config = conf.Configuration()
  File "/app/conf.py", line 35, in __init__
    config['exchanges'] = self.__parse_config(config['exchanges'], 'EXCHANGES')
  File "/app/conf.py", line 48, in __parse_config
    config_fragment[key] = self.__parse_config(config_fragment[key], key_path)
  File "/app/conf.py", line 48, in __parse_config
    config_fragment[key] = self.__parse_config(config_fragment[key], key_path)
  File "/app/conf.py", line 61, in __parse_config
    new_value = bool(distutils.util.strtobool(new_value))
  File "/usr/local/lib/python3.6/distutils/util.py", line 317, in strtobool
    raise ValueError("invalid truth value %r" % (val,))
ValueError: invalid truth value 'false and exchanges_bitfinex_required_enabled=true'

**Comment by shads2** [comment]
settings.env is a list of environment variables it must be configured:

EXCHANGES_BITFINEX_REQUIRED_ENABLED=true
EXCHANGES_BITTREX_REQUIRED_ENABLED=false

**Comment by himanshubotadra** [comment]
Thanks for the quick response. I assume I can do the same changes for Binance as well by making it true and making bittrex false .. 
Is there any key to understand the colour codes of the output that is generated ? 
Sincere thanks for all the efforts for creating this and helping with issues as well. I have it up and running , now just want to make Sure what is the best way to read it and if there is any info related to that please ? 
Also how do we set alerts to our mobile or email please ?

**Comment by shads2** [comment]
Yes you can change it to binance the same way, have a read of https://github.com/AbenezerMamo/crypto-signal/blob/master/doc/FAQ.md it answers the questions about how to configure it. 

The colour red means the indicator is at a buy threshold, white is neutral and blue means it is at a sell threshold for that particular indicator.

**Comment by shads2** [comment]
The link above has been moved into the main Readme

**Comment by himanshubotadra** [comment]
Ok thanks for the color updates. How do we setup alerts on Telegram and email ? Thanks ..

**Comment by shads2** [comment]
Have a read of https://github.com/AbenezerMamo/crypto-signal/blob/master/README.md which has a section on how to configure it.

**Comment by shads2** [comment]
No further updates, I am closing this issue for now.
