### ISSUE TITLE
Cannot set pairs in settings.env

### ISSUE THREAD

**Issue by githeum** [CryptoSignal/crypto-signal#187]
If I place 
SETTINGS_MARKET_PAIRS=ETH/BTC,DOGE/BTC
It will still show me all the paris.

Here is my settings.env
EXCHANGES_BITTREX_REQUIRED_ENABLED=false
EXCHANGES_BINANCE_REQUIRED_ENABLED=true
SETTINGS_MARKET_PAIRS=ETH/BTC,DOGE/BTC

so, I am using Binance.

The output will still be all the pairs from the Binance exchange.

**Comment by shads2** [comment]
Fixed in https://github.com/CryptoSignal/crypto-signal/pull/188

**Comment by shads2** [comment]
Fix merged. New container should be available in the next half hour.
