### ISSUE TITLE
exception handling

### ISSUE THREAD

**Issue by Kooshini** [CryptoSignal/crypto-signal#190]
See the attached error, the app stops when that error happens,  can handle the exception so it doesn't die?

[error.txt](https://github.com/CryptoSignal/crypto-signal/files/1772615/error.txt)

**Comment by shads2** [comment]
Fixed in https://github.com/CryptoSignal/crypto-signal/pull/192 waiting for review.

**Comment by jrbartola** [comment]
Merged
