### ISSUE TITLE
Add installation requirements to README

### ISSUE THREAD

**Issue by l2airj** [CryptoSignal/crypto-signal#195]
Thank you for the file but I would like to know the way to run the file I am using mac

**Comment by shads2** [comment]
Is there some part of the documentation that is confusing? The installation for mac is no different than any other operating system.

**Comment by l2airj** [comment]
But I did not know the way to start the file

**Comment by shads2** [comment]
It's covered in https://github.com/CryptoSignal/crypto-signal#installing-and-running to run the app you run `docker-compose pull && docker-compose run --rm app`

**Comment by l2airj** [comment]
-bash: docker-compose: command not found

**Comment by shads2** [comment]
You need to have docker and docker-compose installed. https://docs.docker.com/docker-for-mac/install/ and https://docs.docker.com/compose/install/

**Comment by rootscript** [comment]
This was one area that was lacking,`installation requirements`.
According to the current docker webpage:
`Docker for Mac`  already includes `Compose` along with other Docker apps, so Mac users do not need to install Compose separately.

**Comment by shads2** [comment]
I'll update the doco to more accurately reflect the install process. I'll close this issue after that has been done.

**Comment by shads2** [comment]
Updated in https://github.com/CryptoSignal/crypto-signal/pull/204
