### ISSUE TITLE
Customizable message templating

### ISSUE THREAD

**Issue by shads2** [CryptoSignal/crypto-signal#206]
Users often want to change the format output of the messages they are receiving. Some form of message templating would allow this.

**Comment by rajnet70** [comment]
Ok great how long will this take.

**Comment by shads2** [comment]
It will happen whenever some one has time to implement it.

**Comment by pitremj** [comment]
I've created a pull for this update however mi not too familiar with GIT so it might of gotten lost message me if you did not receive my update

**Comment by shads2** [comment]
There currently aren't any open PR's for this repo, I think you've opened the PR on the wrong thing?

**Comment by shads2** [comment]
Implemented in https://github.com/CryptoSignal/crypto-signal/pull/237. Not yet feature complete... still documentation pending but this should be merged soon.

**Comment by shads2** [comment]
Merged.
