### ISSUE TITLE
Stateful Notifications

### ISSUE THREAD

**Issue by jevy** [CryptoSignal/crypto-signal#209]
It would be great if the notifications were stateful:

* When the app starts any triggered analysis are labeled as occurring on startup (and therefore may not be recent signals).
* When triggers occur, the notifications happen only once.

**Comment by shads2** [comment]
Implemented in https://github.com/CryptoSignal/crypto-signal/pull/237. Still some additional work until I can merge it, but the core functionality is written.

**Comment by shads2** [comment]
Merged.
