### ISSUE TITLE
RSI period 4 on 5 mins chart

### ISSUE THREAD

**Issue by thehightechsol** [CryptoSignal/crypto-signal#211]
What may the RSI equivalent period in 1 period chart for RSI period 4 on 5 MINS chart.

Will it be RSI period 20 on 1 min chart?

**Comment by shads2** [comment]
I'm afraid I don't understand the question?

**Comment by thehightechsol** [comment]
i rephrase my question ..
 I INTEND to compare rsi on  5 mins chart and 1 min chart simultaneoulsy. And if RSI period 5 in 5 min chart and RSI period 5 in 1 min chart coincides at 20-25 then I intend to make a call. As i cant compare two graphs I intend to plot RSI 5 min chart period 4 over  RSI 1 min chart .

**Comment by shads2** [comment]
Right, at this point we don't have the feature to allow multiple configurations for the same indicator, let alone comparing them against one another. There is a git issue already open for the first part.

So I am going to close this issue as there is already a feature request for this behaviour.
