### ISSUE TITLE
settings.env template

### ISSUE THREAD

**Issue by Kooshini** [CryptoSignal/crypto-signal#212]
create a default settings.env for the project 

e.g. in the repo - settings.env.example with all the settings commented out

### Example settings.env, comment out the settings you need
#SETTINGS_LOGLEVEL=DEBUG
#SETTINGS_UPDATE_INTERVAL=300
#SETTINGS_MARKET_PAIRS=BTC/USD,BTC/USDT

Also maybe you could create a python parser to allow json to settings.env auto generation on your side so if new settings are added to the application the default values are copied to the .example env file

**Comment by shads2** [comment]
We can add something like this, with the latest version of the execution you don't actually need to clone the repo any more to run it so it's a bit weird. But if it helps people then why not ¯\_(ツ)_/¯

**Comment by shads2** [comment]
Implemented in https://github.com/CryptoSignal/crypto-signal/pull/214
