### ISSUE TITLE
Show Indicators Value

### ISSUE THREAD

**Issue by rajnet70** [CryptoSignal/crypto-signal#216]
Need to show indicator values for example  rsi: 38.01875583  stoch_rsi: 80.20798886, for text limitation you can have maybe up to 2 decimal points. Currently indicator hot or cold is a bit vague.

**Comment by shads2** [comment]
This will be solved by previously opened git issue https://github.com/CryptoSignal/crypto-signal/issues/206 . I am closing this for now.
