### ISSUE TITLE
Allow multiple variants of the same indicator

### ISSUE THREAD

**Issue by shads2** [CryptoSignal/crypto-signal#217]
Give the ability to set multiple indicators of the same kind, so you could run (as a random example) EMA15, 20 and 50 if you wanted.

**Comment by cryptohanaan** [comment]
I second that - very important

**Comment by rajnet70** [comment]
👍

**Comment by jrbartola** [comment]
Pending review #218

**Comment by shads2** [comment]
https://github.com/CryptoSignal/crypto-signal/pull/218 approved, more work to be done to be more flexible in support of multiple indicators.

**Comment by shads2** [comment]
Implemented in https://github.com/CryptoSignal/crypto-signal/pull/220 :tada:

**Comment by jrbartola** [comment]
Docs just need to be updated. I'll do that tomorrow when I'm not lazy :P
