### ISSUE TITLE
Add an API to get indicators on demand

### ISSUE THREAD

**Issue by hslimi** [CryptoSignal/crypto-signal#224]
Actually we have results every x period, in several output formats based on settings file.

It would be good if we can have results on demand via REST URLs. 
Something like, we give as an input what we have actually in settings file (pairs, period, ...) and we get as an output a json response.

**Comment by shads2** [comment]
This project is not an API, it's an assistant to manual traders. If you were to write an API on top of the libraries and methodologies we are using for retrieving the data it would be... woefully inadequately slow.
