### ISSUE TITLE
Bug with over 40 day EMA

### ISSUE THREAD

**Issue by robe** [CryptoSignal/crypto-signal#225]
Error:
Traceback (most recent call last):
  File "app.py", line 46, in <module>
    main()
  File "app.py", line 41, in main
    behaviour.run(settings['market_pairs'], settings['output_mode'])
  File "/app/behaviour.py", line 56, in run
    self.__test_strategies(market_data, output_mode)
  File "/app/behaviour.py", line 144, in __test_strategies
    output = self.__get_cli_output(analyzed_data, market_pair)
  File "/app/behaviour.py", line 214, in __get_cli_output
    if indicator['is_hot']:
TypeError: list indices must be integers or slices, not str

Settings.env
EXCHANGES_BITFINEX_REQUIRED_ENABLED=false
EXCHANGES_BINANCE_REQUIRED_ENABLED=true
SETTINGS_MARKET_PAIRS=ETH/BTC,FUN/ETH,EOS/ETH,ICX/ETH,BLZ/ETH,GVT/ETH,VEN/ETH,LINK/ETH,LTC/ETH
SETTINGS_UPDATE_INTERVAL=300
BEHAVIOUR_MOMENTUM_0_ENABLED=false
BEHAVIOUR_ICHIMOKU_0_ENABLED=false
BEHAVIOUR_STOCHASTIC_RSI_0_ENABLED=false
BEHAVIOUR_SMA_CROSSOVER_0_ENABLED=false
BEHAVIOUR_SMA_0_ENABLED=false
BEHAVIOUR_EMA_NUM_INDICATORS=4
BEHAVIOUR_EMA_0_PERIOD_COUNT=8
BEHAVIOUR_EMA_1_PERIOD_COUNT=13
BEHAVIOUR_EMA_2_PERIOD_COUNT=21
BEHAVIOUR_EMA_3_PERIOD_COUNT=45
BEHAVIOUR_EMA_0_CANDLE_PERIOD=1d
BEHAVIOUR_EMA_1_CANDLE_PERIOD=1d
BEHAVIOUR_EMA_2_CANDLE_PERIOD=1d
BEHAVIOUR_EMA_3_CANDLE_PERIOD=1d
BEHAVIOUR_EMA_CROSSOVER_0_PERIOD_COUNT=8/15
BEHAVIOUR_MACD_SL_0_ENABLED=true
BEHAVIOUR_MACD_SL_0_PERIOD_COUNT=21
BEHAVIOUR_MACD_SL_0_CANDLE_PERIOD=1d
BEHAVIOUR_EMA_0_ALERT_ENABLED=false
BEHAVIOUR_EMA_1_ALERT_ENABLED=false
BEHAVIOUR_EMA_2_ALERT_ENABLED=false
BEHAVIOUR_EMA_3_ALERT_ENABLED=false

**Comment by jrbartola** [comment]
Fixed 9985950
