### ISSUE TITLE
Alerts not getting disabled

### ISSUE THREAD

**Issue by rajnet70** [CryptoSignal/crypto-signal#226]
Both for analysis and notifier alerts are not getting disabled, please look into this

**Comment by shads2** [comment]
Can you provide the configuration you are using?

**Comment by rajnet70** [comment]
BEHAVIOUR_RSI_ENABLED=true 
BEHAVIOUR_RSI_ALERT_ENABLED=true 
BEHAVIOUR_STOCHASTIC_RSI_ENABLED=false

Here you go not getting RSI notfication that is true but keep getting Stoch RSI notfication while that is false

**Comment by shads2** [comment]
Which notifier are you using? Please provide the _full_ configuration (without usernames/passwords/api tokens obviously).

**Comment by rajnet70** [comment]
I tried this as well, here you go is this fine? if so still not getting RSI in discord only in terminal and stoch rsi still getting alerts whiles its false

#SETTINGS_LOG_MODE=text 
SETTINGS_OUTPUT_MODE=cli
SETTINGS_UPDATE_INTERVAL=30 
SETTINGS_MARKET_PAIRS=BTC/USDT  
EXCHANGES_BINANCE_REQUIRED_ENABLED=true
BEHAVIOUR_RSI_1_ENABLED=true 
BEHAVIOUR_RSI_ALERT_1_ENABLED=true
BEHAVIOUR_STOCHASTIC_RSI_1_ENABLED=false


NOTIFIERS_DISCORD_REQUIRED_WEBHOOK=XXXXX
NOTIFIERS_DISCORD_REQUIRED_USERNAME=XXXX

**Comment by shads2** [comment]
Thanks, I'll look into this further when I get a chance.

**Comment by rajnet70** [comment]
Ok great!

**Comment by shads2** [comment]
Fixed in https://github.com/CryptoSignal/crypto-signal/pull/238. Waiting for review.
