### ISSUE TITLE
Display candle period in alerts

### ISSUE THREAD

**Issue by tommuhm** [CryptoSignal/crypto-signal#230]
If there are multiple alerts for one indicator on different timeframes then the user does not know the candle period for the received signals.

Example: RSI Alerts for 1h, 30m, 15m
rsi (73.87884888578914): BTC/USDT is cold!
rsi (83.13213181231311): BTC/USDT is cold!
rsi (81.31231212151231): BTC/USDT is cold!

=> what is the candle period for this alerts?

**Comment by shads2** [comment]
Merged your PR to fix this .
