### ISSUE TITLE
"binance has no market NANO/BTC, ignoring"

### ISSUE THREAD

**Issue by orangebutblue** [CryptoSignal/crypto-signal#235]
I started crypto-signal with several coin pairs on binance, and I get the following error/warning:

binance has no market NANO/BTC, ignoring.
binance has no market BCC/BTC, ignoring.
binance has no market YOYO/BTC, ignoring.

even though binance does have all these exchanges.

I'm assuming the problem with NANO is the recent rebranding (XRB) and the problem with BCC is that it's actually BCH. (not sure about YOYO)

**Comment by shads2** [comment]
The Binance API for whatever reason has a weird history of not matching the availability of what is on its UI. I've had similar questions in the past and whenever I've looked into it, it's always just been Binance listing strange things on their API. I think once they even listed a pair that wasn't available on the UI yet.

If you don't specify what markets you want to look at, it will just walk all of the available markets exposed by their API. We don't do anything special with the markets when they are read we just get everything they list.

**Comment by shads2** [comment]
With no follow up questions I am closing this issue for now.
