### ISSUE TITLE
Error with settings output mode json

### ISSUE THREAD

**Issue by Sach97** [CryptoSignal/crypto-signal#239]
Hi everyone, great project ! Unfortunately I wanted to test it out with the json output and I got an error.

**My settings.env:**
`
SETTINGS_OUTPUT_MODE=json
SETTINGS_MARKET_PAIRS=ETH/BTC
SETTINGS_UPDATE_INTERVAL=300
EXCHANGES_BITTREX_REQUIRED_ENABLED=true
SETTINGS_OUTPUT_MODE=json
`

**Error log:**
enabled notifers: []
Starting default analyzer...
Found configured markets: ['ETH/BTC']
Using the following exchange(s): ['bittrex']
Beginning analysis of bittrex
Traceback (most recent call last):
  File "app.py", line 46, in <module>
    main()
  File "app.py", line 41, in main
    behaviour.run(settings['market_pairs'], settings['output_mode'])
  File "/app/behaviour.py", line 57, in run
    new_result = self._test_strategies(market_data, output_mode)
  File "/app/behaviour.py", line 153, in _test_strategies
    output = self._get_json_output(new_result[exchange])
  File "/app/behaviour.py", line 252, in _get_json_output
    indicator['result']['is_hot']
KeyError: 'momentum'

**Comment by shads2** [comment]
This might be related to the notifier overhaul I implemented yesterday, I'll look into this when I get a chance.

**Comment by shads2** [comment]
Fixed in https://github.com/CryptoSignal/crypto-signal/pull/242 waiting for review.

**Comment by shads2** [comment]
Merged
