### ISSUE TITLE
Implement MFI index

### ISSUE THREAD

**Issue by rhamnett** [CryptoSignal/crypto-signal#240]
Hi would someone kindly implement the MFI index from ta-lib? https://mrjbq7.github.io/ta-lib/func_groups/momentum_indicators.html

Looks like it should be a simple refactor of the previous indicators. I will try and get to it next week if nobody manages to take a look.

Thanks

**Comment by shads2** [comment]
Sure, sounds alright to me. I don't know if I will get to it in the week. Trying to crush some of the bugs that have been on the backlog a little while, but we'll see what happens.

**Comment by rhamnett** [comment]
https://github.com/CryptoSignal/crypto-signal/pull/241

**Comment by shads2** [comment]
Merged :)
