### ISSUE TITLE
Add webhook to the notifier templates

### ISSUE THREAD

**Issue by paul-kl** [CryptoSignal/crypto-signal#250]
Instead of using twilio, telegram or discord we could use our prefered method of getting notified once a webhook url is defined.

Thank you!

**Comment by jrbartola** [comment]
I'm not quite sure I understand the request. Could you explain what you mean?

**Comment by paul-kl** [comment]
If a event occurs, the notification should be send as JSON POST to a an API endpoint I defined. From my understanding right now this isn't possible, just several telegram, discord, twilio and so on.

**Comment by shads2** [comment]
I see no reason why we couldn't add this.

**Comment by shads2** [comment]
Implemented in https://github.com/CryptoSignal/crypto-signal/pull/256 awaiting review.

**Comment by shads2** [comment]
merged
