### ISSUE TITLE
Not posting on Discord

### ISSUE THREAD

**Issue by BatorGG** [CryptoSignal/crypto-signal#251]
In my settings.env file I have
```
EXCHANGES_POLONIEX_REQUIRED_ENABLED=true

NOTIFIERS_DISCORD_REQUIRED_WEBHOOK=https://discordapp.com/api/webhooks/...........
NOTIFIERS_DISCORD_REQUIRED_USERNAME=TradingBot
NOTIFIERS_DISCORD_OPTIONAL_AVATAR=https://i.imgur.com/EcTy04J.png

NOTIFIERS_GMAIL_REQUIRED_USERNAME=myemailaddress@gmail.com
NOTIFIERS_GMAIL_REQUIRED_PASSWORD=mypassword
NOTIFIERS_GMAIL_REQUIRED_DESTINATION_EMAILS=myotheremailaddress@gmail.com
```
(I wrote ... instead of my real webhook)

But  when I start the bot, it only says `enabled notifers: ['gmail']`
What did I do wrong?

**Comment by Bzndrtrdr** [comment]
"G" motivation is unclear.

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by shads2** [comment]
I can't see anything glaringly obvious, it's possible that there is a bug right now when you enable multiple notifiers. I'll investigate further when I can.

**Comment by shads2** [comment]
merged
