### ISSUE TITLE
JSON output incorrect with new analyzer structure

### ISSUE THREAD

**Issue by rhamnett** [CryptoSignal/crypto-signal#257]
JSON output is putting the results into a crossover list as per example https://pastebin.ca/4018029

If you have two or more records for an indicator eg RSI, in the json we need to include the indicator's index number so you can tell which result is which. Also see the pastebin link above which contains an example of two RSI values for different candle periods.

JSON output would be much more informative if it contained the candle period (would solve the above) and exchange name. Could you kindly add these?

Thanks

**Comment by shads2** [comment]
merged
