### ISSUE TITLE
issue with script

### ISSUE THREAD

**Issue by tomthedude** [CryptoSignal/crypto-signal#260]
hello,
i have installed the script today, it was working fine until all of the sudden i started getting this errors:
Traceback (most recent call last):
  File "app.py", line 45, in <module>
    main()
  File "app.py", line 39, in main
    behaviour.run(settings['market_pairs'], settings['output_mode'])
  File "/app/behaviour.py", line 62, in run
    new_result = self._test_strategies(market_data, output_mode)
  File "/app/behaviour.py", line 101, in _test_strategies
    self.output[output_mode](new_result[exchange][market_pair], market_pair),
  File "/app/outputs.py", line 47, in to_cli
    if 'is_hot' in analysis['result'].iloc[-1]:
  File "/usr/local/lib/python3.6/site-packages/pandas/core/indexing.py", line 1373, in __getitem__
    return self._getitem_axis(maybe_callable, axis=axis)
  File "/usr/local/lib/python3.6/site-packages/pandas/core/indexing.py", line 1830, in _getitem_axis
    self._is_valid_integer(key, axis)
  File "/usr/local/lib/python3.6/site-packages/pandas/core/indexing.py", line 1713, in _is_valid_integer
    raise IndexError("single positional indexer is out-of-bounds")
IndexError: single positional indexer is out-of-bounds

then the program ofcourse die. (it happens every run now..)
what should i do?
thnak you!

**Comment by shads2** [comment]
Are you able to provide which settings you are using so that I can re-create the issue?

**Comment by tomthedude** [comment]
Hello,
i have ,anaged to track the problem, it happens with some of the coins.
Had a long list, i did manage to delete 3 or 4 coins that were kiiling the app, but apperantly there are much more (it is impossible to run this on all coins - 100% will kill app)
I am attaching a list that now is working for me:
POWR/BTC,MTL/BTC,NEBL/BTC,POE/BTC,HSR/BTC,VEN/BTC,GVT/BTC,AION/BTC,ELF/BTC,LINK/BTC,SUB/BTC,INS/BTC,ENJ/BTC,NULS/BTC,BCPT/BTC,KNC/BTC,ARN/BTC,AST/BTC,WTC/BTC,CND/BTC,GTO/BTC,RCN/BTC,VIBE/BTC,REQ/BTC,BNT/BTC,VIB/BTC,BTS/BTC,FUN/BTC,GAS/BTC,YOYO/BTC,OST/BTC,ETH/BTC,TRX/BTC,XVG/BTC,SC/BTC,ADA/BTC,ZCL/BTC,XRP/BTC,RDD/BTC,BTG/BTC,LTC/BTC,,ADT/BTC,WAVES/BTC,POWR/BTC,XLM/BTC


all of these working 100% fine.
Here is the full list i had, i already deleted few bads but apparently there are more and i am tired of QA lol.:
EOS/BTC,BCC/BTC,XRP/BTC,ICX/BTC,BNB/BTC,ZIL/BTC,ONT/BTC,NCASH/BTC,IOTA/BTC,BCD/BTC,IOST/BTC,NANO/BTC,MTL/BTC,NEBL/BTC,POE/BTC,HSR/BTC,VEN/BTC,GVT/BTC,AION/BTC,ELF/BTC,LINK/BTC,SUB/BTC,INS/BTC,ENJ/BTC,NULS/BTC,BCPT/BTC,KNC/BTC,ARN/BTC,AST/BTC,WTC/BTC,CND/BTC,GTO/BTC,RCN/BTC,VIBE/BTC,REQ/BTC,BNT/BTC,VIB/BTC,BTS/BTC,FUN/BTC,GAS/BTC,YOYO/BTC,OST/BTC,ETH/BTC,TRX/BTC,XVG/BTC,SC/BTC,ADA/BTC,ZCL/BTC,XRP/BTC,RDD/BTC,BTG/BTC,LTC/BTC,ADT/BTC,OMG/BTC,WAVES/BTC,POWR/BTC,XLM/BTC,ETC/BTC,QTUM/BTC,NEO/BTC,XMR/BTC,DGB/BTC,DASH/BTC,GNT/BTC,DOGE/BTC



some bad apples here hehe

Here are my full settings:
SETTINGS_UPDATE_INTERVAL=1800
EXCHANGES_BITTREX_REQUIRED_ENABLED=true
EXCHANGES_BINANCE_REQUIRED_ENABLED=true
NOTIFIERS_TELEGRAM_REQUIRED_TOKEN=xxxxxx
NOTIFIERS_TELEGRAM_REQUIRED_CHAT_ID=xxxxx
INDICATOR_STOCHASTIC_RSI_0_ENABLED=false
NOTIFIERS_TELEGRAM_OPTIONAL_TEMPLATE= {"exchange": "{{exchange}}", "market": "{{market}}", "candls": "{{analysis.config.cand$ (template is working fine...)
SETTINGS_MARKET_PAIRS=POWR/BTC,MTL/BTC,NEBL/BTC,POE/BTC,HSR/BTC,VEN/BTC,GVT/BTC,AION/BTC,ELF/BTC,LINK/BTC,SUB/BTC,INS/BTC,EN$... see above
CROSSOVER_STD_CROSSOVER_0_ENABLED=false
CROSSOVER_EMA_CROSSOVER_0_ENABLED=false
CROSSOVER_SMA_CROSSOVER_0_ENABLED=false
INDICATOR_VWAP_0_ENABLED=false


cheers

**Comment by shads2** [comment]
Thanks I'll have a look into it, we had a huge code change earlier this week and it's introduced one or two new issues. This is likely to be related to that.

**Comment by tomthedude** [comment]
thanks,
another issue i encounter is in the results being sent to telegram i dont get all indicators, only maximum of 4, sometimes even 3...
here is example: (its's json i send to telegram, sometimes there is rsi indicator instead of another one there, but very very rarely)
 {"exchange": "bittrex", "market": "QTUM/BTC", "candls": "1d", {'momentum': '0.00019398'}, "status": "hot" }
 {"exchange": "bittrex", "market": "QTUM/BTC", "candls": "1h", {'mfi': '47.98384288'}, "status": "hot" }
 {"exchange": "bittrex", "market": "QTUM/BTC", "candls": "1h", {'macd': '-0.00002848'}, "status": "cold" }
 {"exchange": "bittrex", "market": "QTUM/BTC", "candls": "1d", {'leading_span_a': '0.00223070', 'leading_span_b': '0.00202448'}, "status": "hot" }

as you can see i get 4 indications, i also have RSI enabled for alerts and all, but still see it only rarely. (for example i think on TRX/BTC its always shown, but not sure.)


please advise.

**Comment by shads2** [comment]
Could you open that as a separate git issue, it helps me immensely when I can track different issues separately.

**Comment by shads2** [comment]
Fixed in https://github.com/CryptoSignal/crypto-signal/pull/265

**Comment by shads2** [comment]
merged
