### ISSUE TITLE
partial data being sent to telegram

### ISSUE THREAD

**Issue by tomthedude** [CryptoSignal/crypto-signal#263]
hello,
 in the results being sent to telegram i dont get all indicators, only maximum of 4, sometimes even 3...
here is example: (its's json i send to telegram, sometimes there is rsi indicator instead of another one there, but very very rarely)
{"exchange": "bittrex", "market": "QTUM/BTC", "candls": "1d", {'momentum': '0.00019120'}, "status": "hot" }
{"exchange": "bittrex", "market": "QTUM/BTC", "candls": "1d", {'mfi': '70.42225908'}, "status": "hot" }
{"exchange": "bittrex", "market": "QTUM/BTC", "candls": "1d", {'macd': '0.00005375'}, "status": "hot" }
{"exchange": "bittrex", "market": "QTUM/BTC", "candls": "1d", {'leading_span_a': '0.00223070', 'leading_span_b': '0.00202448'}, "status": "hot" }

as you can see i get 4 indications, i also have RSI enabled for alerts and all, but still see it only rarely. (for example i think on TRX/BTC its always shown, example:
{"exchange": "bittrex", "market": "TRX/BTC", "candls": "1d", {'momentum': '0.00000277'}, "status": "hot" }
{"exchange": "bittrex", "market": "TRX/BTC", "candls": "1d", {'mfi': '78.77500100'}, "status": "hot" }
{"exchange": "bittrex", "market": "TRX/BTC", "candls": "1d", {'rsi': '71.09614884'}, "status": "cold" }
{"exchange": "bittrex", "market": "TRX/BTC", "candls": "1d", {'macd': '0.00000057'}, "status": "hot" }

and as you can see in TRX it does not show me the leading spans, it is like the results being sent are limited to 4 only, because on the cli i see all indicators...
please advise.

**Comment by shads2** [comment]
The default behaviour (which is configurable) is that it won't re-notify for a status that it already notified you of previously, unless the state changes. Can you confirm that the issue you are seeing is not due to this behaviour?

**Comment by shads2** [comment]
I totally misread your issue description the first time around. I'll look into the message being truncated.

**Comment by tomthedude** [comment]
yeah just to clarify, it never send/sent me all data, i also dont get any info about informants in this message, and also no info about crossovers
just 3-4 indicators MAX, regardless if the values changed or not.
thanks mate.

**Comment by tomthedude** [comment]
update:
it happens also on gamil, so i guess it is not telegram issue but a general issue (this happens in both also with default template and settings)

**Comment by tomthedude** [comment]
another update:
this is getting bizzar lol, i tried to go around this issue, and had a telegram bot that deiplay to me the teminal output, figured i will see all indexes and informants i see in terminal, but when the terminal output get delivred to telegram, this is what i get:
BNT/BTC:

indicators:     momentum #0: 0.00011110ichimoku #0: 0.00048003/0.00045827 
informants:     vwap #0: 0.00681591    bollinger_bands #0: 0.00040086/0.00040086/0.00040086 
crossovers:


again as you can see, only MAX of 4 indicators.... the rest just vanish from the message... 
real odd :|

**Comment by shads2** [comment]
Informants have no hot or cold state, they are purely informational metrics and as such shouldn't 'alert'. They exist to be used in conjunction with things like crossovers that allow you to use their output to create new indicators.

**Comment by tomthedude** [comment]
this one yes, i ham having trouble defining the crossovers, it throws me some error, should i open a new one for it?

**Comment by shads2** [comment]
Yep, open a different issue for that.
