### ISSUE TITLE
Question : Possible to send messages as a bold italic or smileys in telegram?

### ISSUE THREAD

**Issue by deniscolak** [CryptoSignal/crypto-signal#267]
Not issue , just question

**Comment by shads2** [comment]
I'm not really a user of telegram, so I'm not 100% sure what the character encoding of formatted text or emoji's looks like. It _should_ be possible, but I don't know how.

**Comment by tomthedude** [comment]
you should add to the sent string to bot "parse_mode = HTML" (alongside chat_id and text)  and then you can use <b></b> for bold <i></> for italic

**Comment by shads2** [comment]
So it looks like to support bold or italics the parse_mode would have to be html or markdown. I think I would prefer markdown, just to make it consistent with slack and discord. I will add that as a feature.

To send emojis you have to set the escaped unicode string of the emoji... I don't think there's anyway I can make that easier for telegram.

**Comment by shads2** [comment]
Implemented in https://github.com/CryptoSignal/crypto-signal/pull/272. The default parse mode ended up being HTML as some markdown characters are being used in the default message format which can cause issues when there is no matching end pair. That said you can choose to use whatever you like!

**Comment by shads2** [comment]
Merged
