### ISSUE TITLE
still got issued with crossovers, app crashing

### ISSUE THREAD

**Issue by tomthedude** [CryptoSignal/crypto-signal#268]
hello,
i still have a problem with crossovers even after pulling update.
i will past here the error that crashes it soon, mean while, here are my setting, are they OK?
CROSSOVER_STD_CROSSOVER_0_ENABLED=true
CROSSOVER_STD_CROSSOVER_0_ALERT_FREQUENCY=always
CROSSOVER_STD_CROSSOVER_0_KEY_INDICATOR=sma
CROSSOVER_STD_CROSSOVER_0_KEY_INDICATOR_INDEX=0
CROSSOVER_STD_CROSSOVER_0_KEY_SIGNAL=sma
CROSSOVER_STD_CROSSOVER_0_CROSSED_INDICATOR=sma
CROSSOVER_STD_CROSSOVER_0_CROSSED_INDICATOR_INDEX=1
CROSSOVER_STD_CROSSOVER_0_CROSSED_SIGNAL=sma

**Comment by shads2** [comment]
I had the realisation as I went to sleep last night that there was probably another bug in the code base. I had planned to re-open the old issue... but this works too.

**Comment by shads2** [comment]
When this PR https://github.com/CryptoSignal/crypto-signal/pull/271 is merged it should fix the crossover issues.

**Comment by shads2** [comment]
merged
