### ISSUE TITLE
Bollinger bands are the same for upper, middle and lower 

### ISSUE THREAD

**Issue by noenthu** [CryptoSignal/crypto-signal#270]
Noticed this for a large number of crypto pairs where the close values are quite close to 0, the lower, upper, middle values were all returning the same.

![unknown](https://user-images.githubusercontent.com/989601/39402376-3508156e-4b23-11e8-84c0-26e984e6cad2.png)

Appears this is an issue with the underlying TA-Lib. The python wrapper maintained by @mrjbq7 had a similar issue logged at https://github.com/mrjbq7/ta-lib/issues/151

The wheels maintained on the https://www.lfd.uci.edu/~gohlke/pythonlibs/#ta-lib site have a patch already implemented.

**Comment by shads2** [comment]
I'm not sure there is much I can do with this until the ta-lib wrapper releases a fix.

**Comment by shads2** [comment]
The other option is I could adopt another TA library (such as https://tulipindicators.org/bbands) that may not have this particular issue. If I find time I might try that out and see if that is a viable option.

**Comment by shads2** [comment]
Moved bb to new calculation library, appears to be more reliable at calculating small values https://github.com/CryptoSignal/crypto-signal/pull/296

**Comment by shads2** [comment]
merged
