### ISSUE TITLE
more than 1 crossover crashes app

### ISSUE THREAD

**Issue by tomthedude** [CryptoSignal/crypto-signal#274]
Hello,
i have managed to use 1 STD_CROSSOVER, when i try to add 2 more, the app crashed (final error it throws is: Key(something): sma_1  - wierd thing is with out all the EMA crossovers, the sma crossover works just fine... ), here are my settings:

INFORMANT_EMA_NUM_INDICATORS=4
INFORMANT_EMA_0_CANDLE_PERIOD=1h
INFORMANT_EMA_0_CANDLE_PERIOD_COUNT=9
INFORMANT_EMA_1_CANDLE_PERIOD=1h
INFORMANT_EMA_1_CANDLE_PERIOD_COUNT=21
INFORMANT_EMA_2_CANDLE_PERIOD=1h
INFORMANT_EMA_2_CANDLE_PERIOD_COUNT=45
INFORMANT_EMA_3_CANDLE_PERIOD=1h
INFORMANT_EMA_3_CANDLE_PERIOD_COUNT=67
INFORMANT_SMA_NUM_INDICATORS=2
INFORMANT_SMA_0_CANDLE_PERIOD=1h
INFORMANT_SMA_0_PERIOD_COUNT=21
INFORMANT_SMA_1_CANDLE_PERIOD=1h
INFORMANT_SMA_1_PERIOD_COUNT=45
CROSSOVER_STD_CROSSOVER_NUM_INDICATORS=3
CROSSOVER_STD_CROSSOVER_0_ENABLED=true
CROSSOVER_STD_CROSSOVER_0_ALERT_FREQUENCY=always
CROSSOVER_STD_CROSSOVER_0_KEY_INDICATOR=sma
CROSSOVER_STD_CROSSOVER_0_KEY_INDICATOR_INDEX=0
CROSSOVER_STD_CROSSOVER_0_KEY_SIGNAL=sma
CROSSOVER_STD_CROSSOVER_0_CROSSED_INDICATOR=sma
CROSSOVER_STD_CROSSOVER_0_CROSSED_INDICATOR_INDEX=1
CROSSOVER_STD_CROSSOVER_0_CROSSED_SIGNAL=sma
CROSSOVER_STD_CROSSOVER_1_ENABLED=true
CROSSOVER_STD_CROSSOVER_1_ALERT_FREQUENCY=always
CROSSOVER_STD_CROSSOVER_1_KEY_INDICATOR=ema
CROSSOVER_STD_CROSSOVER_1_KEY_INDICATOR_INDEX=0
CROSSOVER_STD_CROSSOVER_1_KEY_SIGNAL=ema
CROSSOVER_STD_CROSSOVER_1_CROSSED_INDICATOR=ema
CROSSOVER_STD_CROSSOVER_1_CROSSED_INDICATOR_INDEX=1
CROSSOVER_STD_CROSSOVER_1_CROSSED_SIGNAL=ema
CROSSOVER_STD_CROSSOVER_2_ENABLED=true
CROSSOVER_STD_CROSSOVER_2_ALERT_FREQUENCY=always
CROSSOVER_STD_CROSSOVER_2_KEY_INDICATOR=ema
CROSSOVER_STD_CROSSOVER_2_KEY_INDICATOR_INDEX=2
CROSSOVER_STD_CROSSOVER_2_KEY_SIGNAL=ema
CROSSOVER_STD_CROSSOVER_2_CROSSED_INDICATOR=ema
CROSSOVER_STD_CROSSOVER_2_CROSSED_INDICATOR_INDEX=3
CROSSOVER_STD_CROSSOVER_2_CROSSED_SIGNAL=ema

thank you

**Comment by shads2** [comment]
Merged
