### ISSUE TITLE
suggestion: making bollinger_bands from informant to indicator

### ISSUE THREAD

**Issue by tomthedude** [CryptoSignal/crypto-signal#276]
hello,
i suggest this because it makes much more sense, since it is a 3 values parameter it doesnt make much sense to cross it, and in order to get the data sent out, you have to either cross informants (doesnt make sense with BB) or make it an indicator (or best option in my opinion is to just let the user choose rather h wants informants being sent or not instead of just not sending them unless they are crossed (and ATM it is not possible to make more than 1 cross, so lost of of lots of data being analyzed and not sent to user.
cheers mate

**Comment by shads2** [comment]
Bollinger band is an informant, it is not a technical indicator that in and of itself carries any meaning on when to buy. It merely tells you that a period of volatility is likely coming if there has been a prolonged period of price stagnation. It can tell you that a period of stagnation has ended if close crosses bb high or bb low, which means it makes sense to track as a cross.

The inability to do more than one cross is a bug that I will squash once I have adequate time to do so, I've been under the weather this week which means I haven't had quite as much time to dedicate.

**Comment by tomthedude** [comment]
"if close crosses bb high or bb low," - there is no such option to in this app to cross vs. price.... unless i send the BB data outside and then compare to the price... so basically i can not do anything with BB atm since i can not cross them with the price since this option does not exist in the app, and i can not send them outside to cross them with the price...
still not undertading why the big NO NO regarding sending talso the informants out... if i want to anylaze the values in my app i have to cross them in crypto-signal just to be able to send them outside and proccess the data the way i want.
please re-consider making all data send-able and not only indicators and crossed informants.. thanks

**Comment by shads2** [comment]
The only reason it doesn't exist yet is because I prioritise bugs and feature requests on git before other work. Nobody has requested OHLCV data to be exposed yet and as a result it has been prioritised lower on my list.

The reason sending informants is off the table at the moment is because they have no "action" point, which means every time it runs I would have to send all of them. This is how the app used to work and people didn't very much like that it would spam them for no reason when there was nothing actionable to do.

**Comment by tomthedude** [comment]
well too bad in my opinion, a lot of unused data.
would be better just to let the each one choose instead of some choosing for all, and add it as a setting...
SETTINGS_SEND_INFORMANTS=true/false

it was already implemented to send as you said... :(
thanks man

**Comment by tomthedude** [comment]
i sadly know nothing about python, not my field of expert, if it was i was happy to assist with this awesome project
