### ISSUE TITLE
Possible "Write output to file" feature?

### ISSUE THREAD

**Issue by dwagenleiter** [CryptoSignal/crypto-signal#278]
Hey guys,

As (possibly) seen in my other issue, I am trying to send the JSON output to a webhook for further processing, i.e. using it for a web interface.

For that, instead of using a webhook to write it into JSON files / a database, it would be a great feature to just write the results into a JSON file directly with a cusomizable naming scheme or maybe something fixed like:

[baseCurrency]_[counterCurrency]_[exchangeName]_[timestamp].json

Would that be possible?

Thanks in advance,
David

**Comment by shads2** [comment]
Given we use docker as the deployment artifact and any state in a docker container is lost when the container is lost I would prefer (at this point in time) not to write the results to a file. That will be confusing for a lot of people, which will place further support burdens on what limited time I have developing this project

**Comment by shads2** [comment]
I don't think I am going to implement this, at this time... if there was a greater ground swell of support I would consider it. Or if some one wanted to make a PR implementing this.

At this stage though I feel like this would be a challenging thing to support and the webhook notifier exists for programmatic use cases which means there is an existing work around for those who really want it.
