### ISSUE TITLE
docker: Error response from daemon: create ./config.yml

### ISSUE THREAD

**Issue by dwagenleiter** [CryptoSignal/crypto-signal#285]
Hi,

I have just installed the latest version (as completely fresh in a new directory) but am getting the following error message:

# docker run --rm -v ./config.yml:/app/config.yml shadowreaver/crypto-signal:master

docker: Error response from daemon: create ./config.yml: "./config.yml" includes invalid characters for a local volume name, only "[a-zA-Z0-9][a-zA-Z0-9_.-]" are allowed. If you intended to pass a host directory, use absolute path.

See 'docker run --help'.

If I try it like this:

# docker run --rm -v config.yml:/app/config.yml shadowreaver/crypto-signal:master

I am getting the following messages and nothing happens:

------
enabled notifers: []
Starting default analyzer...
No configured markets, using all available on exchange.
Using the following exchange(s): []

Sleeping for 300 seconds
------

I have followed the installation instructions, i.e. created the config.yml file. 

My config.yml is as follows:

settings:
    update_interval: 300
    market_pairs:
        - ETH/BTC
        - DOGE/BTC

exchanges:
	bittrex:
        required:
            enabled: true
notifiers:
    webhook:
        required:
            url: http://xxx/webhook.php
indicators:
    rsi:
        - enabled: true
          alert_enabled: true
          alert_frequency: once
          signal:
            - rsi
          hot: 30
          cold: 70
          candle_period: 1d
          period_count: 14
        - enabled: true
          alert_enabled: true
          alert_frequency: once
          signal:
            - rsi
          hot: 30
          cold: 70
          candle_period: 1h
          period_count: 14

informants:
    sma:
        - enabled: true
          signal:
            - sma
          candle_period: 1h
          period_count: 9

Thanks for helping.

**Comment by dvalent** [comment]
Same Errors Here, Im on macOS Sierra 10.12.6 running Docker 18.03

**Comment by shads2** [comment]
Hmmm, I am suspecting that perhaps some versions of docker don't support relative paths. Can you try running `docker run --rm -v $PWD/config.yml:/app/config.yml shadowreaver/crypto-signal:master`

**Comment by dwagenleiter** [comment]
That works for me. And it's Docker 18.03 on Ubuntu 16.04.4 - Thanks!

**Comment by shads2** [comment]
Thanks, I'll update the readme then close this issue 👍
