### ISSUE TITLE
Webhook: IndexError: list index out of range for certain currency pairs

### ISSUE THREAD

**Issue by dwagenleiter** [CryptoSignal/crypto-signal#295]
Hi again,

It seems that certain currency pairs (probable with bad data) produce an "IndexError: list index out of range" when trying to use the webhook.

The full error message is:

**Traceback (most recent call last):
    File "app.py", line 45, in <module>
    main()
  File "app.py", line 39, in main
    behaviour.run(settings['market_pairs'], settings['output_mode'])
  File "/app/behaviour.py", line 65, in run
    self.notifier.notify_all(new_result)
  File "/app/notification.py", line 100, in notify_all
    self.notify_webhook(new_analysis)
  File "/app/notification.py", line 196, in notify_webhook
    new_analysis[exchange][market][indicator_type][indicator][index] = analysis['result'].to_dict(orient='records')[-1]
IndexError: list index out of range**
	  
I have figured out some of the "bad pairs" but apparently it keeps changing. Sometimes they work, sometimes they don't. It might have a tendency to be newer trading pairs.

The bad pairs that I had to exclude so far were: DMT/BTC, BLT/BTC, POLY/BTC, PRO/BTC, XVC/BTC

On Bittrex I was able to "fix" it by always excluding bad pairs, but as I am trying Binance now, that would be a monumental task while trying to actually get all markets in.
	  
Thanks for all the help and work!

**Comment by shads2** [comment]
This should be quite simple to fix.

**Comment by shads2** [comment]
Should be fixed by https://github.com/CryptoSignal/crypto-signal/pull/297 when it's merged.

**Comment by shads2** [comment]
merged
