### ISSUE TITLE
Can't start container

### ISSUE THREAD

**Issue by hackzilla** [CryptoSignal/crypto-signal#303]
I'm not sure if this is a problem with my docker configuration.
I've tried 2 different computers (both Mac).

```
docker run --rm -v $(pwd)/config.yml:/app/config.yml shadowreaver/crypto-signal:master .
docker: Error response from daemon: OCI runtime create failed: container_linux.go:348: starting container process caused "exec: \".\": executable file not found in $PATH": unknown.
```

**Comment by shads2** [comment]
You have a dot at the end of your command, it should work if you remove it.

**Comment by hackzilla** [comment]
That makes sense.

It must have come across when I copied it from the README.md
