### ISSUE TITLE
Crossover: IndexError: list index out of range (Bad data)

### ISSUE THREAD

**Issue by decharel** [CryptoSignal/crypto-signal#304]
After hours of running crypto-signal I get the following error. I assume an error handling could avoid this crossover behaviour when there is bad data.

> Beginning analysis of NEO/USDT
> Exchange supplied bad data for pair NEO/USDT, skipping
> Traceback (most recent call last):
>   File "app.py", line 45, in <module>
>     main()
>   File "app.py", line 39, in main
>     behaviour.run(settings['market_pairs'], settings['output_mode'])
>   File "/app/behaviour.py", line 63, in run
>     new_result = self._test_strategies(market_data, output_mode)
>   File "/app/behaviour.py", line 98, in _test_strategies
>     new_result[exchange][market_pair]
>   File "/app/behaviour.py", line 251, in _get_crossover_results
>     crossed_indicator = new_result[crossover_conf['crossed_indicator_type']][crossover_conf['crossed_indicator']][crossover_conf['crossed_indicator_index']]
> IndexError: list index out of range

**Comment by december-soul** [comment]
maybe this can help you.
#299 

not a good fix but it works

**Comment by tacorepublic** [comment]
I'm seeing the same thing and noticing that it's retrying. Posting error here just in case it helps

`Beginning analysis of WTC/BTC
Too many retries fetching information for pair WTC/BTC, skipping
Too many retries fetching information for pair WTC/BTC, skipping
Too many retries fetching information for pair WTC/BTC, skipping
Too many retries fetching information for pair WTC/BTC, skipping
Too many retries fetching information for pair WTC/BTC, skipping
Too many retries fetching information for pair WTC/BTC, skipping
Traceback (most recent call last):
  File "app.py", line 45, in <module>
    main()
  File "app.py", line 39, in main
    behaviour.run(settings['market_pairs'], settings['output_mode'])
  File "/app/behaviour.py", line 63, in run
    new_result = self._test_strategies(market_data, output_mode)
  File "/app/behaviour.py", line 98, in _test_strategies
    new_result[exchange][market_pair]
  File "/app/behaviour.py", line 250, in _get_crossover_results
    key_indicator = new_result[crossover_conf['key_indicator_type']][crossover_conf['key_indicator']][crossover_conf['key_indicator_index']]
IndexError: list index out of range
`

**Comment by shads2** [comment]
I think that's actually a separate problem, but it will probably help me track down this one.

**Comment by mattiasgeniar** [comment]
Getting a similar error on EMA crossovers;

```
Beginning analysis of HSR/BTC
No historical data provided returned by exchange.
Invalid data encountered while processing pair HSR/BTC, skipping
Traceback (most recent call last):
  File "app.py", line 45, in <module>
    main()
  File "app.py", line 39, in main
    behaviour.run(settings['market_pairs'], settings['output_mode'])
  File "/app/behaviour.py", line 63, in run
    new_result = self._test_strategies(market_data, output_mode)
  File "/app/behaviour.py", line 98, in _test_strategies
    new_result[exchange][market_pair]
  File "/app/behaviour.py", line 250, in _get_crossover_results
    key_indicator = new_result[crossover_conf['key_indicator_type']][crossover_conf['key_indicator']][crossover_conf['key_indicator_index']]
IndexError: list index out of range
```

**Comment by heartsmith** [comment]
I run the app over all pairs on bittrex and also get the same error. Any fix?


Beginning analysis of BCH/BTC
No historical data provided returned by exchange.
Invalid data encountered while processing pair BCH/BTC, skipping
No historical data provided returned by exchange.
Invalid data encountered while processing pair BCH/BTC, skipping
No historical data provided returned by exchange.
Invalid data encountered while processing pair BCH/BTC, skipping
No historical data provided returned by exchange.
Invalid data encountered while processing pair BCH/BTC, skipping
No historical data provided returned by exchange.
Invalid data encountered while processing pair BCH/BTC, skipping
Traceback (most recent call last):
  File "app.py", line 45, in <module>
    main()
  File "app.py", line 39, in main
    behaviour.run(settings['market_pairs'], settings['output_mode'])
  File "/app/behaviour.py", line 63, in run
    new_result = self._test_strategies(market_data, output_mode)
  File "/app/behaviour.py", line 98, in _test_strategies
    new_result[exchange][market_pair]
  File "/app/behaviour.py", line 250, in _get_crossover_results
    key_indicator = new_result[crossover_conf['key_indicator_type']][crossover_conf['key_indicator']][crossover_conf['key_indicator_index']]
IndexError: list index out of range

**Comment by alonsovargas3** [comment]
Choose a different pair like BTC/USDT to make sure it’s not an issue with
the BCH pair.

**Comment by heartsmith** [comment]
Hi @alonsovargas3 , everything goes fine if I only run it over a specific pair like BTC/USDT. Weirdly, the same error occurred on BHC/BTC regardless on which market exchange.

**Comment by alonsovargas3** [comment]
That's because BCH is no longer a coin - it forked and you have two:
BCHABC/BTC and BCHBV/BTC - I believe they both inherited the BCH historical
data.

**Comment by laliux** [comment]
Today, April 4, these seem to be the correct pairs on Bittrex:

BSV/BTC - Bitcoin SV
BCH/BTC - Bitcoin Cash

Candle periods: '1m', '5m', '30m', '1h', '1d'

**Comment by alonsovargas3** [comment]
Good info. Also, in the error message I saw the following:

Invalid data encountered while processing pair HSR/BTC, skipping

Looks like you just need to make sure your config file has the right pairs.

**Comment by heartsmith** [comment]
So far what I need to do to scan all pairs is to list all pairs in the config except the ones which failed, right?
Roger that. Thank you, everyone! 💃

**Comment by laliux** [comment]
The program ignores invalid pairs, It doesn't cause any error because of that.

By the way, take a look at the **development** branch. There are many interesting things in the process.
