### ISSUE TITLE
Discord client does not work without valid avatar

### ISSUE THREAD

**Issue by jjmilburn** [CryptoSignal/crypto-signal#305]
Despite the avatar field being listed as optional, placing `None` into the configuration file will cause the webhook to return 400.

If you manually change the following line in the discord notifier client file to explicitly set the `avatar_url` to None, everything works great.

```
        self.discord_client = Webhook(webhook, avatar_url=None)
```

However, simply putting "None" in the config file does not work.

**Comment by shads2** [comment]
You need to add "null" that is the Yaml equivalent of "None" http://yaml.org/type/null.html
