### ISSUE TITLE
Bollinger Bands -- lowerband/upperband inverted

### ISSUE THREAD

**Issue by fdk0** [CryptoSignal/crypto-signal#306]
This is the configuration I am using for the informants for bollinger_bands

> bollinger_bands:

        - enabled: true
          signal:
            - upperband
          candle_period: 15m
        - enabled: true
          signal:
            - middleband
          candle_period: 15m
        - enabled: true
          signal:
            - lowerband
          candle_period: 15m

Comparing the number I get in the console and tradingview it seams that the lowerband and upperband are inverted.. a few screenshots of the console and the BollingerBand for the same pair on tradingview:
![screen shot 2018-05-27 at 20 33 21](https://user-images.githubusercontent.com/35744779/40591110-32282d1c-620b-11e8-99be-7e1d0eaba9af.png)
![screen shot 2018-05-27 at 20 41 53](https://user-images.githubusercontent.com/35744779/40591112-374ddddc-620b-11e8-8aa4-84d7950cb4a3.png)

Thanks!

**Comment by fdk0** [comment]
probably the issue is in this line in bollinger_bands.py:
`              bb_values['upperband'][index] = bb_data[0][data_index]
                bb_values['middleband'][index] = bb_data[1][data_index]
                bb_values['lowerband'][index] = bb_data[2][data_index] `

thanks.

**Comment by shads2** [comment]
https://github.com/CryptoSignal/crypto-signal/pull/307 fixes this issue.
