### ISSUE TITLE
Windows 10 home

### ISSUE THREAD

**Issue by Cryptoseen** [CryptoSignal/crypto-signal#311]
Hi, Docker Ce does not support Windows 10 home. Is there any other way I can use it? 

Note: I use the system: Windows 10 bash (Ubuntu) 

Thank you.

**Comment by shads2** [comment]
You can use the old docker-toolbox method, though that is significantly harder to setup https://docs.docker.com/toolbox/toolbox_install_windows/

**Comment by Cryptoseen** [comment]
Thank you
