### ISSUE TITLE
Mac / No configured markets

### ISSUE THREAD

**Issue by Gwendir** [CryptoSignal/crypto-signal#318]
Hi All,

I've downloaded docker and edit the config.yml. Openend cmd and executed the next code on my Mac terminal program: 
docker run --rm -v $PWD/config.yml:/app/config.yml shadowreaver/crypto-signal:master

Output:
------
enabled notifers: []
Starting default analyzer...
No configured markets, using all available on exchange.
Using the following exchange(s): []

Sleeping for 300 seconds
------
I Think Docker can't read the config file. I put it in the Applications root .... is that correct?

**Comment by Gwendir** [comment]
Solved! config.yml must be in the user root.

**Comment by akaymakci** [comment]
For Windows 10 users where is the correct location for config.yml file in Windows 10? Could you please answer this asap?
