### ISSUE TITLE
key error 'alert_enable' 

### ISSUE THREAD

**Issue by rohan-prasad** [CryptoSignal/crypto-signal#322]
Beginning analysis of ETH/USDT
ETH/USDT:	

indicators:	rsi #0: 48.14556446 	rsi #1: 50.91178011 	
informants:	sma #0: 462.64333333 	sma #1: 463.28428571 	
crossovers:	std_crossover #0: 462.64333333/463.28428571 	

Traceback (most recent call last):
  File "app.py", line 45, in <module>
    main()
  File "app.py", line 39, in main
    behaviour.run(settings['market_pairs'], settings['output_mode'])
  File "/app/behaviour.py", line 65, in run
    self.notifier.notify_all(new_result)
  File "/app/notification.py", line 102, in notify_all
    self.notify_discord(new_analysis)
  File "/app/notification.py", line 119, in notify_discord
    self.notifier_config['discord']['optional']['template']
  File "/app/notification.py", line 319, in _indicator_message_templater
    if not analysis['config']['alert_enabled']:
KeyError: 'alert_enabled'

**Comment by Rohan48** [comment]
settings:
    
    update_interval: 300
    market_pairs:
        - ETH/BTC
        - ETH/USDT
        - BTC/USDT
        - LTC/BTC
    
exchanges:
    binance:
        required:
            enabled: true

    bittrex:
        required:
            enabled: false             
indicators:
  momentum:
    - enabled: false
      alert_enabled: true
      alert_frequency: once
      signal:
        - momentum
      hot: 0
      cold: 0
      candle_period: 1d
      period_count: 10
  mfi:
    - enabled: false
      alert_enabled: true
      alert_frequency: once
      signal:
        - mfi
      hot: 20
      cold: 80
      candle_period: 15m
      period_count: 14
  obv:
    - enabled: false
      alert_enabled: true
      alert_frequency: once
      signal:
        - obv
      hot: 0
      cold: 0
      candle_period: 1d
  rsi:
    - enabled: true
      alert_enabled: true
      alert_frequency: once
      signal:
        - rsi
      hot: 50
      cold: 70
      candle_period: 1d
      period_count: 14
    - enabled: true
      alert_frequency: once
      signal:
        - rsi
      hot: 50
      cold: 70
      candle_period: 1h
      period_count: 14
  stoch_rsi:
    - enabled: false
      alert_enabled: true
      alert_frequency: once
      signal:
        - stoch_rsi
      hot: 20
      cold: 80
      candle_period: 4h
      period_count: 15
  macd:
    - enabled: false
      alert_enabled: true
      alert_frequency: once
      signal:
        - macd
      hot: 0
      cold: 0
      candle_period: 1h
  ichimoku:
    - enabled: false
      alert_enabled: true
      alert_frequency: once
      signal:
        - leading_span_a
        - leading_span_b
      hot: true
      cold: true
      candle_period: 4h
informants:
  vwap:
    - enabled: false
      signal:
        - vwap
      candle_period: 4h
      period_count: 15
  sma:
    - enabled: true
      signal:
        - sma
      candle_period: 1h
      period_count: 9
    - enabled: true
      signal:
        - sma
      candle_period: 1h
      period_count: 21
  ema:
    - enabled: false
      signal:
        - ema
      candle_period: 4h
      period_count: 15
  bollinger_bands:
    - enabled: false
      signal:
        - upperband
        - middleband
        - lowerband
      candle_period: 15m
      signal:
        - upperband
        - middleband
        - lowerband
      candle_period: 1h
  ohlcv:
    - enabled: false
      signal:
        - close
      candle_period: 4h
      period_count: 15

crossovers:
    std_crossover:
        - enabled: true
          alert_enabled: true
          alert_frequency: once
          key_indicator: sma
          key_indicator_index: 0
          key_indicator_type: informants
          key_signal: sma
          crossed_indicator: sma
          crossed_indicator_index: 1
          crossed_indicator_type: informants
          crossed_signal: sma

          
notifiers:
    discord:
        required:
            webhook: xxx
            username: xxx
        optional:
            avatar: http://abcd1234/avatar.png
            template: "{{exchange}}-{{market}}-{{indicator}}-{{indicator_number}} is {{status}}!{{ '\n' -}}"
