### ISSUE TITLE
Candle_Period error

### ISSUE THREAD

**Issue by jimmyhong23** [CryptoSignal/crypto-signal#332]
Starting default analyzer...
Found configured markets: ['XRP/USDT']
Using the following exchange(s): ['binance']
Beginning analysis of binance
Beginning analysis of XRP/USDT
Traceback (most recent call last):
  File "app.py", line 45, in <module>
    main()
  File "app.py", line 39, in main
    behaviour.run(settings['market_pairs'], settings['output_mode'])
  File "/app/behaviour.py", line 63, in run
    new_result = self._test_strategies(market_data, output_mode)
  File "/app/behaviour.py", line 89, in _test_strategies
    market_pair
  File "/app/behaviour.py", line 137, in _get_indicator_results
    candle_period = indicator_conf['candle_period']
KeyError: 'candle_period'

How do I fix this error?

**Comment by alkhachatryan** [comment]
How did you fix it??

**Comment by 0x-Johnson** [comment]
I have received. Thanks.Johnson

**Comment by alkhachatryan** [comment]
**IF YOU CAME HERE WITH THE SAME ISSUE I HAVE, YOU CAN CLONE MY REPO, WHICH HAS A LOT OF FIXES INCLUDING THIS ONE**

https://github.com/krypt0ra/station
