### ISSUE TITLE
Program crashed after start

### ISSUE THREAD

**Issue by lewtran** [CryptoSignal/crypto-signal#353]
Branch: develop
There is no error and the program says: "All workers are running!" but nothing is running.
I've tried to run with docker or in python enviroment.

**Comment by laliux** [comment]
Hi @lewtran 

If you're using the stdout notifier just check the latest code. I wrote a fix a few minutes ago.

If not, tell me what is the command you're executing and the output you're getting.

Best

**Comment by lewtran** [comment]
Thank you for your response @laliux 
I'm using Telegram notifier.
I've tried to execute two commands:
`docker run --rm -ti -v $PWD/app:/app dev/crypto-signals:latest`
The output is:
`/usr/local/bin/python: can't open file 'app.py': [Errno 2] No such file or directory`

`docker run --rm -di -v $PWD/app:/app dev/crypto-signals:latest`
And here is the output:
'05be1706538ba0088e4eece7b36757bcdcb8e789c3d29378bb4c55980fc09a2b'

It's seem like the docker is running but crashed right away and nothing happend.

**Comment by laliux** [comment]
@lewtran 

Can u show your config file ...

**Comment by lewtran** [comment]
@laliux Thank you and please close this issue.
The problem comes from my Docker version, some package cannot build correctly but without and error. After I upgrade docker, the program runs fine.
