### ISSUE TITLE
configured market pair and exchange but can't analyze them

### ISSUE THREAD

**Issue by Ava520X** [CryptoSignal/crypto-signal#372]
Hi,
Follow the example configuration with market pair and exchanged enable true. When I run it, the result is unexpected. Can anyone help?
Here is the result: 
Starting default analyzer...
No configured markets, using all available on exchange.
Using the following exchange(s): []

Sleeping for 300 seconds

-------------

configure yaml :
----------
settings:
    log_level: INFO
    update_interval: 500
    market_pairs:
        - BTC/USDT
        - ETH/USDT
        - LTC/BTC
        - XMR/BTC

exchanges:
    binance:
        required:
            enabled: true
    bittrex:
        required:
            enabled: true

indicators:
    rsi:
        - enabled: true
          alert_enabled: false
          alert_frequency: once
          signal:
            - rsi
          hot: 30
          cold: 70
          candle_period: 1h
          period_count: 50
        - enabled: true
          alert_enabled: true
          alert_frequency: once
          signal:
            - rsi
          hot: 30
          cold: 70
          candle_period: 5m
          period_count: 14

**Comment by Ava520X** [comment]
it solved

**Comment by suatkummuz** [comment]
how to fix

**Comment by chugh-ak5** [comment]
Hi, does anyone know the solution for this? Please let me know how to go about it

**Comment by cherryleafroad** [comment]
Yeah, same problem for me too
