### ISSUE TITLE
it's stop after few days :/

### ISSUE THREAD

**Issue by n4v3d** [CryptoSignal/crypto-signal#378]
hello dear laliux
dev/crypto-signals:latest  is stoped after few days
i try to use 
docker run -d --restart unless-stopped dev/crypto-signals:latest
docker run -d --restart always dev/crypto-signals:latest

but it's restart after every 1 minute or less

ubuntu 16
latest docker version
 thanks in advanced

**Comment by laliux** [comment]
Checking the config file you shared on Discord, you need to change your "update_interval" value. 3600 is a good option.
