### ISSUE TITLE
ma cross indicator problem

### ISSUE THREAD

**Issue by n4v3d** [CryptoSignal/crypto-signal#379]
hi 
i use ma_Cross indicator but it just send cold alert
with config below :
         - enabled: true
          candle_period: 4h
          alert_enabled: true
          alert_frequency: once
          exponential: true
          ma_fast: 10
          ma_slow: 50
          signal:
            - close
          mute_cold: false

**Comment by laliux** [comment]
A lot of people is using this indicator and no one has reported that problem.
