### ISSUE TITLE
Support for Binance futures

### ISSUE THREAD

**Issue by just-a-normal-human** [CryptoSignal/Crypto-Signal#385]
Hi! 
Do you support binance futures, if so, am I supposed to put in certain market pairs or enable another exchange?
If not, do you plan on implementing it?

Thanks in advance!

**Comment by yaroodf2** [comment]
Hi
When will a copy be used to support the binance futures version?
It is enough to use STREAM_URL = 'wss: //fstream3.binance.com/' in the web socket source and the binance futures functions

**Comment by laliux** [comment]
Hey @just-a-normal-human , @yaroodf2 

No plans to implement that feature just for Binance, the idea of ​​this project is that work (in the better way) with multiple exchanges.

Best
