### ISSUE TITLE
OBV indicator throws exception no shape attribute in outputs.py

### ISSUE THREAD

**Issue by robe** [CryptoSignal/Crypto-Signal#395]
OBV indicator throws an exception in outputs.py

**Comment by laliux** [comment]
Hey,..

Be sure you are working with develop branch - https://github.com/CryptoSignal/Crypto-Signal/blob/develop/README.md

If u want share me your config file, then I can check it.

Best

**Comment by laliux** [comment]
Closed due to no answer.
