### ISSUE TITLE
No configured markets

### ISSUE THREAD

**Issue by wowhugo** [CryptoSignal/Crypto-Signal#396]
hi,

I am new to here, and have tried to set the config list. But I got following words:

Starting default analyzer...
No configured markets, using all available on exchange.
Using the following exchange(s): []

and then it repeated all the time. 
The app is updated. but still the same.
Did I do something wrong?

Thanks  a lot.

**Comment by laliux** [comment]
Hey..

Be sure you are working with develop branch, https://github.com/CryptoSignal/Crypto-Signal/blob/develop/README.md

Also,.. check this sample config file, https://pastebin.com/xEa5m2sZ

Best

**Comment by laliux** [comment]
Closed due to no answer.

**Comment by gyankov** [comment]
Hi @laliux, I tried your suggestion, however, after switching to develop and following the steps from the dev branch, I get an error that app.py is not found:

![image](https://user-images.githubusercontent.com/16634965/109657675-6ec5ae00-7b6e-11eb-8eeb-7f28a3c421bf.png)

Got any ideas?
