### ISSUE TITLE
Patter screening on the charts? 

### ISSUE THREAD

**Issue by Jzarecta** [CryptoSignal/Crypto-Signal#401]
I wonder if its possible to combine this with the ZigZag library and be able to identify patterns such as triangles, head and shoulers, double tops/bottoms, and other formations. Similar to this. 
[ZigZag charting](https://d1p5pyutve46t9.cloudfront.net/wp-content/uploads/2013/11/FTSE-100_21-475x324.jpg)

**Comment by laliux** [comment]
Hey @Jzarecta .. 
It is not planned to add any feature like that.
