### ISSUE TITLE
Error while doing your 5th step : Build your own Docker image

### ISSUE THREAD

**Issue by bluetyphoon77** [CryptoSignal/Crypto-Signal#407]
I did this line like you recommend : docker build -t dev/crypto-signals:latest

And I have this error 
"docker build" requires exactly 1 argument.
See 'docker build --help'.
Usage:  docker build [OPTIONS] PATH | URL | -
Build an image from a Dockerfile

By the way, from which folder should I run this command ?

Thanks

**Comment by laliux** [comment]
Hey @bluetyphoon77 

I think you are missing a DOT at the end of docker command.

`docker build -t dev/crypto-signals:latest .`

Run from root folder of the proyect.

Best

**Comment by bluetyphoon77** [comment]
Thanks a lot Eduardo !
It works now :)
I'm in test mode.
Do you know why, even if I set only 2 indicators to check in my config, I have all indicators notified ? LOL
Thanks alot

________________________________

**Comment by laliux** [comment]
@bluetyphoon77 

I need to see your config file so I can try to identify the problem. In the mean time check this sample config file: https://pastebin.com/xEa5m2sZ

Best

**Comment by bluetyphoon77** [comment]
Thanks again for your answer.
My config is so simple compared to yours 😉
But where should I put it ? in app folder ? or main cryptosignal folder ?

here it is attached

I left THETABTC to test
But I still have those notifs LOL
[cid:36604a04-479d-48e2-b6c5-f3a3a58e77d5]



________________________________

**Comment by bluetyphoon77** [comment]
Sorry it seems my screenshots or attachments did not go through.
This is what I have inside my conf.... only !

settings:
  update_interval: 300
  market_pairs:
    - THETA/BTC
    
exchanges:
  binance:
    required:
      enabled: true

notifiers:
    telegram:
        required:
            token: 
            chat_id: 
        optional:
            parse_mode: html
            template: "{{exchange}}-{{market}}-{{indicator}}-{{indicator_number}} is {{status}}!{{ '\n' -}}"
          
indicators:
    rsi:
        - enabled: true
          alert_enabled: true
          alert_frequency: once
          signal:
            - rsi
          hot: 30
          cold: 50
          hot_label: We Are In Oversold!
          cold_label: Attention! Overbought!
          candle_period: 1d
          period_count: 14
    mfi:
        - enabled: true
          alert_enabled: true
          alert_frequency: once
          signal:
            - mfi
          hot: 30
          cold: 50
          hot_label: We Are In Oversold!
          cold_label: Attention! Overbought!
          candle_period: 1d
          period_count: 12

**Comment by bluetyphoon77** [comment]
Would be weird, but do we have to rebuild every time I change my config file ?
thanks again

**Comment by laliux** [comment]
Config file must be in "app" folder.

Is not necesary to rebuild after each change on config file, just stop your running docker and run again.

You should **explicitly** disable all indicators you dont use. Check app/defaults.yml as reference.

Increase your update_interval: 300, this time is in seconds. With that value you are running analysis each 5mins, but you are using 1d candle periods,. doesn't make much sense.

Best

**Comment by bluetyphoon77** [comment]
Thanks again Eduardo !
I was doing more tests ... and you confirm what I realized about the disable ! ;) thanks
Can you just explain to me one last thing please ;) I do not understand the way the levels work (hot/cold)
Hot mean "when RSI goes below this level or goes above it" ?
And for Cold ?

I did not find how to use combination of multiple indicators to be hot
and I see you added filters to RIS ;) I will try to understand what is this ;) ....

thanks again
PS: you are right for 300 ;)

**Comment by bluetyphoon77** [comment]
And the formatting is weird... when I set the pairs it just take the first and last :) any advice ?
Thanks again !

**Comment by laliux** [comment]
Conditionals are not available in this project, hopefully soon I can integrate changes by @w1ld3r.

**Comment by bluetyphoon77** [comment]
But it is already integrated in the fork ! Link is above ;)
I just don't find how to contact dev to know how to make it work :(

**Comment by w1ld3r** [comment]
Hello @bluetyphoon77, for any problem using my fork please create an issue in the fork.
Also before creating a issue please take a look at the documentation -> https://github.com/w1ld3r/crypto-signal/blob/develop/docs/config.md#8-conditionals

**Comment by bluetyphoon77** [comment]
Hi Eduardo !!!
I've managed to understand and find all solutions besides ONE !
I'd love if you can help.
I see you use STOCHRSI in your config.
Why are you using it ? Because I've tested it and getting only wrong values, for stoch, k, and d !
Have you checked the values and compared them with tradingview ?
Cheeers

________________________________

**Comment by laliux** [comment]
The file I shared with you is just an example, it is not my own configuration file.

As I already mentioned in another thread, I will review the StochRSI when I have a little time :)

**Comment by bluetyphoon77** [comment]
Thanks for your answer Eduardo. I also sent an issue into the TA-lib support. It seems they have problems with STOCHRSI. But I don't understand their programmer language LOL, so it will be useful if you can translate to me the solution, even if it means not using this TA-lib anymore and chosing another library !
Thansk a lot 😉

________________________________
