### ISSUE TITLE
Running without docker

### ISSUE THREAD

**Issue by tirouj** [CryptoSignal/Crypto-Signal#410]
Hello

I need to run the app on my windows server so I am not able to use docker.
Could you please let me know how to run the app without using the docker?

Thanks for your help

**Comment by laliux** [comment]
Hey @tirouj 

The main issue when running in MS Windows is installation of TA-lib. It is a core module for crypto-signal, if you can solve it, you are ready.

Then install all python modules listed on app/requirements-step-1.txt and app/requirements-step-2.txt

Finally run `python app.py`

Best

**Comment by tirouj** [comment]
Thanks!

For those who have same need, this was very helpful after testing other solutions:

https://blog.quantinsti.com/install-ta-lib-python/

**Comment by tirouj** [comment]
Hi @laliux 

I did all but at the end I have an error which says :

Traceback (most recent call last):
  File "app/app.py", line 108, in <module>
    main()
  File "app/app.py", line 24, in main
    config = Configuration()
  File "c:\Signals\crypto-signal\app\conf.py", line 18, in __init__
    with open('defaults.yml', 'r') as config_file:
FileNotFoundError: [Errno 2] No such file or directory: 'defaults.yml'


I hope you can help. 

thanks

**Comment by laliux** [comment]
Sorry @tirouj , I can't replicate error, it is running fine.

`
PS C:\dev\Crypto-Signal\app> pwd                                                                                                            
Path
----
C:\dev\Crypto-Signal\app


PS C:\dev\Crypto-Signal\app> python app.py                                                                                                  Found configured markets: ['ATOM/USDT', 'BNB/USDT', 'BAT/USDT', 'BCH/USDT', 'EOS/USDT', 'ENJ/USDT', 'ETH/USDT', 'IOTA/USDT', 'IOST/USDT', 'LTC/USDT', 'LINK/USDT', 'ONT/USDT', 'OMG/USDT', 'MATIC/USDT', 'NANO/USDT', 'QTUM/USDT', 'XRP/USDT', 'ZEC/USDT', 'ZIL/USDT', 'ZRX/USDT']
enabled notifers: ['telegram']
Starting Worker-1
Starting default analyzer...
Using the following exchange(s): ['binance']
Getting data for ['ETH/USDT', 'BNB/USDT', 'LTC/USDT', 'QTUM/USDT', 'XRP/USDT', 'EOS/USDT', 'IOTA/USDT', 'ONT/USDT', 'BCH/USDT', 'LINK/USDT', 'ZIL/USDT', 'ZRX/USDT', 'BAT/USDT', 'ZEC/USDT', 'IOST/USDT', 'NANO/USDT', 'OMG/USDT', 'ENJ/USDT', 'MATIC/USDT', 'ATOM/USDT']

....
`

**Comment by tirouj** [comment]
I changed the current directory to app directory and it worked fine.

I only see the following in the output, not sure if it's important or not:

libifcoremd.dll    00007FFF6D083B58  Unknown               Unknown  Unknown
KERNELBASE.dll     00007FFF9D2B361F  Unknown               Unknown  Unknown
KERNEL32.DLL       00007FFF9E5D13D2  Unknown               Unknown  Unknown
ntdll.dll          00007FFFA00D03C4  Unknown               Unknown  Unknown

**Comment by laliux** [comment]
Weird...

I don't know what is that :| 

I'm not using native Windows in this moment, I ran from VirtualBox just to test.

I used python 3.7.9, and executed from Powershell .
