### ISSUE TITLE
how to use crossovers

### ISSUE THREAD

**Issue by tsenchialee** [CryptoSignal/Crypto-Signal#417]
I know that indicator is hot when the faster moving average crosses over the slower moving average in the latest candlestick, and is cold when the faster moving average dips below the slower moving average in the latest candlestick.

the crossovers happen when the indicator goes from cold to hot, or from hot to cold, so does it need to save the last status of indicator to determine the notification when the status changes?

**Comment by laliux** [comment]
@tsenchialee 

I recommend you to use the **Moving Average Crossover** indicator. Check the README in develop branch.

https://github.com/CryptoSignal/Crypto-Signal/blob/develop/README.md
