### ISSUE TITLE
Web Notifier differences between master and develop branch

### ISSUE THREAD

**Issue by salmonweb** [CryptoSignal/Crypto-Signal#419]
Apologies, more of an ask for help with the differences rather than any issue.

I've just moved over from the master branch to develop and getting to grips with the differences in the web hook notifications. Is it correct that I'm now receiving individual signals for each metric / indicator per coin. They seem to be grouped by the candle periods? Before this, they used to come in one signal. Not sure if there's a setting I'm missing, ideally I'd like to group all notifications per coin in to a single signal.

Thanks for any help in advance, absolutely awesome project!

**Comment by laliux** [comment]
@salmonweb yes, the structure of messages sent to webhook was changed on develop branch.

**Comment by tsenchialee** [comment]
it's better to group  all notifications per coin in to a signal data. how to do this?
