### ISSUE TITLE
Webhook Message

### ISSUE THREAD

**Issue by shiftcryptomyid** [CryptoSignal/Crypto-Signal#432]
How to make a custom message for webhook...

as far as i read config.md there no example for custom webhook message.

**Comment by laliux** [comment]
Hey.. @shiftcryptomyid 

First, take a look on README in develop branch. Next,. on your webhook you receive the "raw" data about the notification, build the custom message is in your side, you will have all the data.

**Comment by shiftcryptomyid** [comment]
so the  parameter "messages" have **all** the data, but in "raw"..
okay now i just need to separate them to custom message i want to build.
is this right?
