### ISSUE TITLE
error response from daemon

### ISSUE THREAD

**Issue by chomanoh** [CryptoSignal/Crypto-Signal#442]
My config file is in the "app" folder, I have checkedout dev, my docker with its image are ok.

I am new to Docker so I can't find the solution.

btw I tried the different ways to call the directory in the console.

![image](https://user-images.githubusercontent.com/89634012/131160915-7b82a4b6-5e37-43ec-a57f-eae9e3052dd2.png)

thanks

**Comment by laliux** [comment]
Hey @chomanoh ,

Use PowerShell, rather than CMD. $PWD doesnt work in CMD.

**Comment by chomanoh** [comment]
Ok thanks !
