### ISSUE TITLE
Asking script to check al bases from coin - not writing every base

### ISSUE THREAD

**Issue by bluetyphoon77** [CryptoSignal/Crypto-Signal#452]
Hi, 
Rather than setting THETA/BTC, THETA/BNB,...
Is it possible to use star or something else to ask the script to check all the bases for a coin ?
thanks

**Comment by laliux** [comment]
@bluetyphoon77 

First, be sure u are working with code in **develop** branch,. next, check the doc about "All pairs" -> https://github.com/CryptoSignal/Crypto-Signal/blob/develop/README.md

**Comment by bluetyphoon77** [comment]
Thanks for your answer ;)
Good to know !! Great you improved all this.
Do we still have the ability to change settings from Telegram ?
And what I was asking is not to select ALL USDT from an exchange for example, but set my listed coins :
XMR
ADA
LUNA,....
and set a general option asking the bot to check all preferred bases (usdt, BNB, btc for example) for my listed coins
 :)
 if not possible I'll write each pair no problem

**Comment by laliux** [comment]
@bluetyphoon77 

Ok, ok, I understand.. 

That is not possible for the moment.

**Comment by bluetyphoon77** [comment]
ah ok. Good to know.
