### ISSUE TITLE
STOCH RSI k value is not right compared to tradingview

### ISSUE THREAD

**Issue by bluetyphoon77** [CryptoSignal/Crypto-Signal#453]
How can we ensure to have the right value ? thanks

**Comment by laliux** [comment]
Hey @bluetyphoon77 

Be sure u are working with code in **develop** branch. I recently rewrote the StochRSI code.

**Comment by bluetyphoon77** [comment]
Great !!! Thanks a lot, I did not pay attention to this branch ! :)
