### ISSUE TITLE
Is it possible to define a different trigger for each coin ?

### ISSUE THREAD

**Issue by bluetyphoon77** [CryptoSignal/Crypto-Signal#454]
rather than having for example the same RSI trigger for all coins listed
thanks in advance

**Comment by laliux** [comment]
@bluetyphoon77 

No, that is not possible, As u say, all indicators are applied to all configured pairs.

**Comment by bluetyphoon77** [comment]
ok thanks, pity :)
I'll try to find a dev, fork and add that when I have the time,
cheeers and great work by the way !
