### ISSUE TITLE
gmail forbids a third party app login and operates

### ISSUE THREAD

**Issue by lfzCarlosC** [CryptoSignal/Crypto-Signal#459]
per the notice from gmail that:

"On May 30, you may lose access to apps that are using less secure sign-in technology cryptalsender1@gmail.com To help keep your account secure, Google will no longer support the use of third-party apps or devices which ask you to sign in to your Google Account using only your username and password. Instead, you’ll need to sign in using Sign in with Google or other more secure technologies, like OAuth 2.0. Learn more"

now using username and password to login is not possible for a third party app

**Comment by alkhachatryan** [comment]
You can try this fork: https://github.com/krypt0ra/station
It's under an active support and there are dozens of errors fixed and there is completed dockerization. If you will still have an issue there, just create a issue: https://github.com/krypt0ra/station/issues/new?assignees=alkhachatryan&labels=&projects=&template=bug_report.md&title=%5BBUG%5D
