### ISSUE TITLE
installation problem 

### ISSUE THREAD

**Issue by peterabj** [CryptoSignal/Crypto-Signal#463]
Hi. 
I am having troubles getting the code to work. 
I downloaded the repo , docker desktop , python 3.10 and I am using PyCharm as an ide. 
i created a config file in the app folder and downloaded all the requirements. But when I try to run "docker build -t ${DOCKER_IMAGE_NAME}:${GIT_BRANCH}" . I am getting this error.
![Screenshot 2022-08-18 121999](https://user-images.githubusercontent.com/102736128/186124600-0ebac839-63c3-4557-ac63-1672ae564db3.png)

**Comment by 0x-Johnson** [comment]
I have received. Thanks.Johnson

**Comment by alkhachatryan** [comment]
You can try this fork: https://github.com/krypt0ra/station
It's under an active support and there are dozens of errors fixed and there is completed dockerization. If you will still have an issue there, just create a issue: https://github.com/krypt0ra/station/issues/new?assignees=alkhachatryan&labels=&projects=&template=bug_report.md&title=%5BBUG%5D
