### ISSUE TITLE
Alert problem

### ISSUE THREAD

**Issue by chanever** [CryptoSignal/Crypto-Signal#471]
Hello. I solved previous problem and was running the program.
and there were some problems.

Question : the alert is made just once.
I want to sent alert everytime this program running.
I mean, if you see 'alert_frequency' in config.yml, you can see 'once' next to 'alert frequencey'.

but is there any way to change signal alert frequency?

**Comment by alkhachatryan** [comment]
You can try this fork: https://github.com/krypt0ra/station
It's under an active support and there are dozens of errors fixed and there is completed dockerization. If you will still have an issue there, just create a issue: https://github.com/krypt0ra/station/issues/new?assignees=alkhachatryan&labels=&projects=&template=bug_report.md&title=%5BBUG%5D
