### ISSUE TITLE
How to get an alert when an order is filled, not based on indicators

### ISSUE THREAD

**Issue by QGB** [CryptoSignal/Crypto-Signal#474]
like this

```
trade_events: 
  order_filled:
    - enabled: true    
```

**Comment by laliux** [comment]
@QGB that is not possible, it works only with indicators.

**Comment by QGB** [comment]
> @QGB that is not possible, it works only with indicators.

Is there another project to do this？

**Comment by alkhachatryan** [comment]
You can try this fork: https://github.com/krypt0ra/station
It's under an active support and there are dozens of errors fixed and there is completed dockerization. If you will still have an issue there, just create a issue: https://github.com/krypt0ra/station/issues/new?assignees=alkhachatryan&labels=&projects=&template=bug_report.md&title=%5BBUG%5D
