### ISSUE TITLE
XTB

### ISSUE THREAD

**Issue by pmiguelr** [CryptoSignal/Crypto-Signal#486]
This code work with XTB ?

**Comment by alkhachatryan** [comment]
You can try this fork: https://github.com/krypt0ra/station
It's under an active support and there are dozens of errors fixed and there is completed dockerization. If you will still have an issue there, just create a issue: https://github.com/krypt0ra/station/issues/new?assignees=alkhachatryan&labels=&projects=&template=bug_report.md&title=%5BBUG%5D
